<div class="modal-dialog">
	<div class="modal-content form-container">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title">Play audio</h4>
		</div>
		<div class="modal-body">
			<center>
				<audio src="<?php echo $this->src; ?>" autoplay="true" type="audio/x-wav" controls="">
					
				</audio>
			</center>
		</div>
	</div>
</div>
