<div class="row">
<?php
    foreach($this->subcategories as $subcategory){
        $string =
            "<div class=\"col-sm-12 subcategory-tile\">
                <a href=\"/play/index/subcategory?id=$subcategory[id]\">
                    <div class='col-sm-3'>
                        <img src=\"$subcategory[icon]\">
                    </div>
                    <div class='col-sm-6'>
                        <h4>$subcategory[title]</h4>
                    </div>

                </a>
            </div>";
        echo $string;
    }
?>