<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html>
	<head>
		<title>Didier Drogba được Hiệp hội cây viết bóng đá vinh danh</title>
		<meta name="keywords" content="đọc báo, doc bao, tin tức,tin tuc,dantri, vnexpress,tin bong da" >
		<meta name="descriptions" content="Đọc báo với tin tức cập nhật 24h" >
		<meta charset="UTF-8">
		<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1.0" />
		<meta name="HandheldFriendly" content="true" />
		<link href='/assets/qplayvn/css/g_font_css.css' rel='stylesheet' type='text/css'>
		<link href='/assets/qplayvn/css/g_font_css_2.css' rel='stylesheet' type='text/css'>
		<link href="/assets/qplayvn/css/common.css" type="text/css" rel="stylesheet">
		<link href="/assets/qplayvn/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css" >
		<link href="/assets/qplayvn/css/idangerous.swiper.css" media="screen" rel="stylesheet" type="text/css" >
		<link href="/assets/qplayvn/css/home.css" media="screen" rel="stylesheet" type="text/css" >
		<link href="/assets/qplayvn/css/swiper.css" media="screen" rel="stylesheet" type="text/css" >
		<link rel="shortcut icon" href="/images/icon/favio.png" />
		<link rel="icon" href="/images/icon/favio.png" />
		
		<script type="text/javascript" src="/assets/qplayvn/js/jquery-1.9.1.min.js"></script>
		<script type="text/javascript" src="/assets/qplayvn/js/idangerous.swiper.js"></script>
		<script type="text/javascript" src="/assets/qplayvn/js/jquery.grid-a-licious.js"></script>
		<script type="text/javascript" src="/assets/qplayvn/js/scroll.js"></script>
		<script type="text/javascript" src="/assets/qplayvn/js/common.js"></script>
	</head>
	<body>
		{% for (var i=0; i < 5; i++) { %}
			<a href="{%=i%}" >afaw</a>
		{% } %}		
	</body>
</html>
